apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: chatbot-oct9-pr-patch-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-oct9-pr-patch-3 
  name: chatbot-oct9-pr-patch-3
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: chatbot-oct9-pr-patch-3 
